---
title: "Manasi Anand"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{css, echo = FALSE}
h1, h2, h3 {text-align: center}
```

### Email: ma2337@cornell.edu

<br>

#### Education: 

PhD in Natural Resources, Cornell University [2021-Present]{style="float:right"}

MSc in Biodiversity, Conservation and Management, University of Oxford[2016-2017]{style="float:right"}

BSc in Chemistry, Botany and Environmental Science, Mount Carmel College[2013-2016]{style="float:right"}

<br>

#### Profess Experience:

Researcher, Indian Institute for Human Settlements(IIHS)[2019-2020]{style="float:right"}

Researcher, Center for Study of Science, Technology and Policy(CSTEP)[2018-2019]{style="float:right"}

Intern, Ashoka Trust for Research in Ecology and the Environment(ATREE)[2014-2015]{style="float:right"}

<br>

#### Publications

Anand, M. and Mulyani, M., 2020. Advancing ‘Environmental Subjectivity’ in the realm of neoliberal forest governance: Conservation subject creation in the Lokkere Reserve Forest, India. Geoforum, 110, pp.106-115.


